# Generated by Django 5.1.6 on 2025-03-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_negative',
        ),
    ]
